apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frr-daemonset
  namespace: default
  labels:
    app: frr-daemonset
spec:
  selector:
    matchLabels:
      name: frr-daemonset
  template:
    metadata: 
      labels:
        app: frr
        name: frr-daemonset
    spec:
      hostNetwork: true
      volumes:
        - name: frr-config
          configMap:
            name: frr-config
      containers:
      - name: frr-daemonset
        image: docker.io/frrouting/frr
        volumeMounts:
        - mountPath: "/etc/frr"
          name: frr-config
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW","SYS_ADMIN"]

